-- 001_initial.sql
-- Migration inicial para o PRD NoCode Folio

-- Extensão para UUID (caso não exista)
create extension if not exists "uuid-ossp";

-- Tabela: perfis
create table if not exists public.perfis (
  id bigint generated by default as identity primary key,
  usuario_id uuid references auth.users(id) on delete cascade not null,
  slug text unique not null,
  nome_completo text not null default '',
  bio text not null default '',
  avatar_url text,
  configuracao_tema jsonb,
  created_at timestamptz not null default now()
);

-- Tabela: blocos
create table if not exists public.blocos (
  id bigint generated by default as identity primary key,
  perfil_id bigint references public.perfis(id) on delete cascade not null,
  tipo text not null check (tipo in ('link','imagem','texto','mapa','video')),
  titulo text,
  conteudo jsonb not null default '{}'::jsonb,
  colunas smallint not null default 1 check (colunas between 1 and 4),
  linhas smallint not null default 1 check (linhas between 1 and 2),
  ordem smallint not null default 0,
  visivel boolean not null default true,
  created_at timestamptz not null default now()
);

-- Índices
create index if not exists idx_perfis_slug on public.perfis(slug);
create index if not exists idx_perfis_usuario_id on public.perfis(usuario_id);
create index if not exists idx_blocos_perfil_id on public.blocos(perfil_id);
create index if not exists idx_blocos_ordem on public.blocos(perfil_id, ordem);

-- RLS
alter table public.perfis enable row level security;
alter table public.blocos enable row level security;

-- Políticas: perfis
create policy "perfis_select_publico" on public.perfis
  for select using (true);

create policy "perfis_insert_proprio" on public.perfis
  for insert with check (auth.uid() = usuario_id);

create policy "perfis_update_proprio" on public.perfis
  for update using (auth.uid() = usuario_id);

-- Políticas: blocos
create policy "blocos_select_publico" on public.blocos
  for select using (true);

create policy "blocos_insert_dono" on public.blocos
  for insert with check (
    exists (
      select 1 from public.perfis
      where perfis.id = blocos.perfil_id
        and perfis.usuario_id = auth.uid()
    )
  );

create policy "blocos_update_dono" on public.blocos
  for update using (
    exists (
      select 1 from public.perfis
      where perfis.id = blocos.perfil_id
        and perfis.usuario_id = auth.uid()
    )
  );

create policy "blocos_delete_dono" on public.blocos
  for delete using (
    exists (
      select 1 from public.perfis
      where perfis.id = blocos.perfil_id
        and perfis.usuario_id = auth.uid()
    )
  );

-- Storage: bucket avatars
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'avatars',
  'avatars',
  true,
  5242880,
  array['image/png','image/jpeg','image/webp','image/gif']::text[]
)
on conflict (id) do nothing;

-- Storage policies
create policy "avatars_select_publico" on storage.objects
  for select using (bucket_id = 'avatars');

create policy "avatars_insert_dono" on storage.objects
  for insert with check (
    bucket_id = 'avatars'
    and auth.uid()::text = (storage.foldername(name))[1]
  );

create policy "avatars_update_dono" on storage.objects
  for update using (
    bucket_id = 'avatars'
    and auth.uid()::text = (storage.foldername(name))[1]
  );

create policy "avatars_delete_dono" on storage.objects
  for delete using (
    bucket_id = 'avatars'
    and auth.uid()::text = (storage.foldername(name))[1]
  );
